spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pzn_redis_cache
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update